### ISSUE TITLE
Incorrect OpsManager AMI in JSON File

### ISSUE THREAD

**Issue by charlesrichard** [Pivotal-Field-Engineering/PCF_AWS_CloudFormation#1]
Hi, the OpsManager AMI for US-EAST listed in the JSON file is incorrect. The correct value is  ami-1e4e7976. Thanks!

**Comment by ruthea** [comment]
replaced the default AMI to this value- thank you!  It's likely the Elastic Runtime is a little outdated also, will update as a new S3 accessible version becomes available.

**Comment by ruthea** [comment]
Now has the official 1.4 ops manager AMI!
