### ISSUE TITLE
us-east-1b availability zone no longer exists

### ISSUE THREAD

**Issue by charlesrichard** [Pivotal-Field-Engineering/PCF_AWS_CloudFormation#2]
The JSON file requests the us-east-1b availability zone. This no longer exists. I found success using us-east-1a. Maybe update to this or c, d, or e. Thanks!

**Comment by ruthea** [comment]
Hi Chuck,
I am able to deploy using the default (us-east-1b).  Is it possible that
you tried to run a CF script when that AZ was down?? Or is there something
I might be missing?

thx,
Austin

On Fri, Apr 3, 2015 at 2:38 PM, Chuck Svoboda notifications@github.com
wrote:

> The JSON file requests the us-east-1b availability zone. This no longer
> exists. I found success using us-east-1a. Maybe update to this or c, d, or
> e. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2
> .

## 

Austin Rutherford | Director, Field Strategy and Operations | Mobile:
612-386-4197 | Twitter: @AP_Rutherford

Pivotal.io

**Comment by charlesrichard** [comment]
Hmmm... I tried today and it failed. Not 100% on the significance, but
us-east-1b is not listed on the EC2 dashboard anymore. You'd think if it
were just down, it would show but with that status. Screen capture attached!

​

Chuck Svoboda
Senior Field Engineer - Pivotal
443-537-7823
csvoboda@pivotal.io

**Comment by selisha-pivotal** [comment]
Every AWS account has a different mapping of AZs - so you cannot assure 
that all people have access to the same AZs - and AZ names are mapped to 
physically AZs differently between accounts.

For eample in my account us-east-1a might map to physical AZ 1, but in 
your account it may map to physical AZ 2. This is an intentional construct.

CloudFormation templates should not hard-code AZ names, rather, it 
should be a parameter that can be entered at runtime.

> Chuck Svoboda mailto:notifications@github.com
> 4 April 2015 08:11
> Hmmm... I tried today and it failed. Not 100% on the significance, but
> us-east-1b is not listed on the EC2 dashboard anymore. You'd think if it
> were just down, it would show but with that status. Screen capture 
> attached!
> 
> ​
> 
> Chuck Svoboda
> Senior Field Engineer - Pivotal
> 443-537-7823
> csvoboda@pivotal.io
> 
> On Fri, Apr 3, 2015 at 5:00 PM, Austin Rutherford 
> notifications@github.com
> wrote:
> 
> > Hi Chuck,
> > I am able to deploy using the default (us-east-1b). Is it possible that
> > you tried to run a CF script when that AZ was down?? Or is there 
> > something
> > I might be missing?
> > 
> > thx,
> > Austin
> > 
> > On Fri, Apr 3, 2015 at 2:38 PM, Chuck Svoboda notifications@github.com
> > wrote:
> > 
> > > The JSON file requests the us-east-1b availability zone. This no 
> > > longer
> > > exists. I found success using us-east-1a. Maybe update to this or 
> > > c, d,
> > > or
> > > e. Thanks!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2
> > 
> > > .
> > 
> > ## 
> > 
> > Austin Rutherford | Director, Field Strategy and Operations | Mobile:
> > 612-386-4197 | Twitter: @AP_Rutherford
> > 
> > Pivotal.io
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-89418321
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-89421303.
> 
> Chuck Svoboda mailto:notifications@github.com
> 4 April 2015 06:38
> 
> The JSON file requests the us-east-1b availability zone. This no 
> longer exists. I found success using us-east-1a. Maybe update to this 
> or c, d, or e. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2.

## 

Simon Elisha
CTO & Director of Field Engineering - Australia & New Zealand
Mobile: +61 417 656 364
e-mail: selisha@pivotal.io mailto:selisha@pivotal.io
http://www.gopivotal.com
pivotal.io http://pivotal.io

**Comment by charlesrichard** [comment]
I'm tracking. Maybe the answer is to remove the default value from the
CloudFormation script? Thoughts?

Chuck Svoboda
Senior Field Engineer - Pivotal
443-537-7823
csvoboda@pivotal.io

**Comment by selisha-pivotal** [comment]
Taking out the default and adding a comment the the field to the effect 
of "enter a valid AZ for your account" would be a good move.

> Chuck Svoboda mailto:notifications@github.com
> 7 April 2015 12:08
> I'm tracking. Maybe the answer is to remove the default value from the
> CloudFormation script? Thoughts?
> 
> Chuck Svoboda
> Senior Field Engineer - Pivotal
> 443-537-7823
> csvoboda@pivotal.io
> 
> On Mon, Apr 6, 2015 at 7:42 PM, selisha-pivotal notifications@github.com
> wrote:
> 
> > Every AWS account has a different mapping of AZs - so you cannot assure
> > that all people have access to the same AZs - and AZ names are mapped to
> > physically AZs differently between accounts.
> > 
> > For eample in my account us-east-1a might map to physical AZ 1, but in
> > your account it may map to physical AZ 2. This is an intentional 
> > construct.
> > 
> > CloudFormation templates should not hard-code AZ names, rather, it
> > should be a parameter that can be entered at runtime.
> > 
> > > Chuck Svoboda mailto:notifications@github.com
> > > 4 April 2015 08:11
> > > Hmmm... I tried today and it failed. Not 100% on the significance, but
> > > us-east-1b is not listed on the EC2 dashboard anymore. You'd think 
> > > if it
> > > were just down, it would show but with that status. Screen capture
> > > attached!
> > > 
> > > ​
> > > 
> > > Chuck Svoboda
> > > Senior Field Engineer - Pivotal
> > > 443-537-7823
> > > csvoboda@pivotal.io
> > > 
> > > On Fri, Apr 3, 2015 at 5:00 PM, Austin Rutherford
> > > notifications@github.com
> > > wrote:
> > > 
> > > > Hi Chuck,
> > > > I am able to deploy using the default (us-east-1b). Is it 
> > > > possible that
> > > > you tried to run a CF script when that AZ was down?? Or is there
> > > > something
> > > > I might be missing?
> > > > 
> > > > thx,
> > > > Austin
> > > > 
> > > > On Fri, Apr 3, 2015 at 2:38 PM, Chuck Svoboda <
> > > > notifications@github.com>
> > > > wrote:
> > > > 
> > > > > The JSON file requests the us-east-1b availability zone. This no
> > > > > longer
> > > > > exists. I found success using us-east-1a. Maybe update to this or
> > > > > c, d,
> > > > > or
> > > > > e. Thanks!
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Austin Rutherford | Director, Field Strategy and Operations | 
> > > > Mobile:
> > > > 612-386-4197 | Twitter: @AP_Rutherford
> > > > 
> > > > Pivotal.io
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > 
> > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-89418321
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-89421303
> > 
> > > .
> > > 
> > > Chuck Svoboda mailto:notifications@github.com
> > > 4 April 2015 06:38
> > > 
> > > The JSON file requests the us-east-1b availability zone. This no
> > > longer exists. I found success using us-east-1a. Maybe update to this
> > > or c, d, or e. Thanks!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2
> > 
> > > .
> > 
> > ## 
> > 
> > Simon Elisha
> > CTO & Director of Field Engineering - Australia & New Zealand
> > Mobile: +61 417 656 364
> > e-mail: selisha@pivotal.io mailto:selisha@pivotal.io
> > http://www.gopivotal.com
> > pivotal.io http://pivotal.io
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-90286000
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-90315268.
> 
> Chuck Svoboda mailto:notifications@github.com
> 4 April 2015 06:38
> 
> The JSON file requests the us-east-1b availability zone. This no 
> longer exists. I found success using us-east-1a. Maybe update to this 
> or c, d, or e. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2.

## 

Simon Elisha
CTO & Director of Field Engineering - Australia & New Zealand
Mobile: +61 417 656 364
e-mail: selisha@pivotal.io mailto:selisha@pivotal.io
http://www.gopivotal.com
pivotal.io http://pivotal.io

**Comment by ruthea** [comment]
Interesting...  great conversation.  I made a change.  It goes with an
assumption that we don't really care which AZ it goes into, just that it
works (at least for now!).  So by selecting a region (at this point only
"us-east-1" has the AMI), it will get AZ's that are legitimate for that
user (using fn:GetAZ) within specified region.  I just put up on github.
It seemed to work for me - let me know your feedback.  We can certainly
delete the default value for AZ if this doesn't work (just trying to keep
this as easy as possible).

thanks,
Austin

On Mon, Apr 6, 2015 at 9:14 PM, selisha-pivotal notifications@github.com
wrote:

> Taking out the default and adding a comment the the field to the effect
> of "enter a valid AZ for your account" would be a good move.
> 
> > Chuck Svoboda mailto:notifications@github.com
> > 7 April 2015 12:08
> > 
> > I'm tracking. Maybe the answer is to remove the default value from the
> > CloudFormation script? Thoughts?
> > 
> > Chuck Svoboda
> > Senior Field Engineer - Pivotal
> > 443-537-7823
> > csvoboda@pivotal.io
> > 
> > On Mon, Apr 6, 2015 at 7:42 PM, selisha-pivotal <
> > notifications@github.com>
> > wrote:
> > 
> > > Every AWS account has a different mapping of AZs - so you cannot assure
> > > that all people have access to the same AZs - and AZ names are mapped
> > > to
> > > physically AZs differently between accounts.
> > > 
> > > For eample in my account us-east-1a might map to physical AZ 1, but in
> > > your account it may map to physical AZ 2. This is an intentional
> > > construct.
> > > 
> > > CloudFormation templates should not hard-code AZ names, rather, it
> > > should be a parameter that can be entered at runtime.
> > > 
> > > > Chuck Svoboda mailto:notifications@github.com
> > > > 4 April 2015 08:11
> > > > Hmmm... I tried today and it failed. Not 100% on the significance,
> > > > but
> > > > us-east-1b is not listed on the EC2 dashboard anymore. You'd think
> > > > if it
> > > > were just down, it would show but with that status. Screen capture
> > > > attached!
> > > > 
> > > > ​
> > > > 
> > > > Chuck Svoboda
> > > > Senior Field Engineer - Pivotal
> > > > 443-537-7823
> > > > csvoboda@pivotal.io
> > > > 
> > > > On Fri, Apr 3, 2015 at 5:00 PM, Austin Rutherford
> > > > notifications@github.com
> > > > wrote:
> > > > 
> > > > > Hi Chuck,
> > > > > I am able to deploy using the default (us-east-1b). Is it
> > > > > possible that
> > > > > you tried to run a CF script when that AZ was down?? Or is there
> > > > > something
> > > > > I might be missing?
> > > > > 
> > > > > thx,
> > > > > Austin
> > > > > 
> > > > > On Fri, Apr 3, 2015 at 2:38 PM, Chuck Svoboda <
> > > > > notifications@github.com>
> > > > > wrote:
> > > > > 
> > > > > > The JSON file requests the us-east-1b availability zone. This no
> > > > > > longer
> > > > > > exists. I found success using us-east-1a. Maybe update to this or
> > > > > > c, d,
> > > > > > or
> > > > > > e. Thanks!
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2
> > 
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Austin Rutherford | Director, Field Strategy and Operations |
> > > > > Mobile:
> > > > > 612-386-4197 | Twitter: @AP_Rutherford
> > > > > 
> > > > > Pivotal.io
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > 
> > > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-89418321
> > 
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-89421303
> > 
> > > > .
> > > > 
> > > > Chuck Svoboda mailto:notifications@github.com
> > > > 4 April 2015 06:38
> > > > 
> > > > The JSON file requests the us-east-1b availability zone. This no
> > > > longer exists. I found success using us-east-1a. Maybe update to this
> > > > or c, d, or e. Thanks!
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Simon Elisha
> > > CTO & Director of Field Engineering - Australia & New Zealand
> > > Mobile: +61 417 656 364
> > > e-mail: selisha@pivotal.io mailto:selisha@pivotal.io
> > > http://www.gopivotal.com
> > > pivotal.io http://pivotal.io
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > <
> > > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-90286000
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-90315268
> > .
> > 
> > Chuck Svoboda mailto:notifications@github.com
> > 4 April 2015 06:38
> > 
> > The JSON file requests the us-east-1b availability zone. This no
> > longer exists. I found success using us-east-1a. Maybe update to this
> > or c, d, or e. Thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2
> > .
> 
> ## 
> 
> Simon Elisha
> CTO & Director of Field Engineering - Australia & New Zealand
> Mobile: +61 417 656 364
> e-mail: selisha@pivotal.io mailto:selisha@pivotal.io
> http://www.gopivotal.com
> pivotal.io http://pivotal.io
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-90316689
> .

## 

Austin Rutherford | Director, Field Strategy and Operations | Mobile:
612-386-4197 | Twitter: @AP_Rutherford

Pivotal.io

**Comment by selisha-pivotal** [comment]
Correct Austin that the AMI in the Region is available to all AZs in 
that Region. So as long as everything uses the same AZ (in terms of 
Subnets etc) then you are good to go!

> Austin Rutherford mailto:notifications@github.com
> 7 April 2015 15:36
> Interesting... great conversation. I made a change. It goes with an
> assumption that we don't really care which AZ it goes into, just that it
> works (at least for now!). So by selecting a region (at this point only
> "us-east-1" has the AMI), it will get AZ's that are legitimate for that
> user (using fn:GetAZ) within specified region. I just put up on github.
> It seemed to work for me - let me know your feedback. We can certainly
> delete the default value for AZ if this doesn't work (just trying to keep
> this as easy as possible).
> 
> thanks,
> Austin
> 
> On Mon, Apr 6, 2015 at 9:14 PM, selisha-pivotal notifications@github.com
> wrote:
> 
> > Taking out the default and adding a comment the the field to the effect
> > of "enter a valid AZ for your account" would be a good move.
> > 
> > > Chuck Svoboda mailto:notifications@github.com
> > > 7 April 2015 12:08
> > > 
> > > I'm tracking. Maybe the answer is to remove the default value from the
> > > CloudFormation script? Thoughts?
> > > 
> > > Chuck Svoboda
> > > Senior Field Engineer - Pivotal
> > > 443-537-7823
> > > csvoboda@pivotal.io
> > > 
> > > On Mon, Apr 6, 2015 at 7:42 PM, selisha-pivotal <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Every AWS account has a different mapping of AZs - so you cannot 
> > > > assure
> > > > that all people have access to the same AZs - and AZ names are 
> > > > mapped
> > > > to
> > > > physically AZs differently between accounts.
> > > > 
> > > > For eample in my account us-east-1a might map to physical AZ 1, 
> > > > but in
> > > > your account it may map to physical AZ 2. This is an intentional
> > > > construct.
> > > > 
> > > > CloudFormation templates should not hard-code AZ names, rather, it
> > > > should be a parameter that can be entered at runtime.
> > > > 
> > > > > Chuck Svoboda mailto:notifications@github.com
> > > > > 4 April 2015 08:11
> > > > > Hmmm... I tried today and it failed. Not 100% on the significance,
> > > > > but
> > > > > us-east-1b is not listed on the EC2 dashboard anymore. You'd think
> > > > > if it
> > > > > were just down, it would show but with that status. Screen capture
> > > > > attached!
> > > > > 
> > > > > ​
> > > > > 
> > > > > Chuck Svoboda
> > > > > Senior Field Engineer - Pivotal
> > > > > 443-537-7823
> > > > > csvoboda@pivotal.io
> > > > > 
> > > > > On Fri, Apr 3, 2015 at 5:00 PM, Austin Rutherford
> > > > > notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > Hi Chuck,
> > > > > > I am able to deploy using the default (us-east-1b). Is it
> > > > > > possible that
> > > > > > you tried to run a CF script when that AZ was down?? Or is there
> > > > > > something
> > > > > > I might be missing?
> > > > > > 
> > > > > > thx,
> > > > > > Austin
> > > > > > 
> > > > > > On Fri, Apr 3, 2015 at 2:38 PM, Chuck Svoboda <
> > > > > > notifications@github.com>
> > > > > > wrote:
> > > > > > 
> > > > > > > The JSON file requests the us-east-1b availability zone. 
> > > > > > > This no
> > > > > > > longer
> > > > > > > exists. I found success using us-east-1a. Maybe update to 
> > > > > > > this or
> > > > > > > c, d,
> > > > > > > or
> > > > > > > e. Thanks!
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2
> > 
> > > > > > > .
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Austin Rutherford | Director, Field Strategy and Operations |
> > > > > > Mobile:
> > > > > > 612-386-4197 | Twitter: @AP_Rutherford
> > > > > > 
> > > > > > Pivotal.io
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > 
> > > > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-89418321
> > 
> > > > > > .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-89421303
> > 
> > > > > .
> > > > > 
> > > > > Chuck Svoboda mailto:notifications@github.com
> > > > > 4 April 2015 06:38
> > > > > 
> > > > > The JSON file requests the us-east-1b availability zone. This no
> > > > > longer exists. I found success using us-east-1a. Maybe update 
> > > > > to this
> > > > > or c, d, or e. Thanks!
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Simon Elisha
> > > > CTO & Director of Field Engineering - Australia & New Zealand
> > > > Mobile: +61 417 656 364
> > > > e-mail: selisha@pivotal.io mailto:selisha@pivotal.io
> > > > http://www.gopivotal.com
> > > > pivotal.io http://pivotal.io
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > 
> > > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-90286000
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-90315268
> > 
> > > .
> > > 
> > > Chuck Svoboda mailto:notifications@github.com
> > > 4 April 2015 06:38
> > > 
> > > The JSON file requests the us-east-1b availability zone. This no
> > > longer exists. I found success using us-east-1a. Maybe update to this
> > > or c, d, or e. Thanks!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2
> > 
> > > .
> > 
> > ## 
> > 
> > Simon Elisha
> > CTO & Director of Field Engineering - Australia & New Zealand
> > Mobile: +61 417 656 364
> > e-mail: selisha@pivotal.io mailto:selisha@pivotal.io
> > http://www.gopivotal.com
> > pivotal.io http://pivotal.io
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-90316689
> > .
> 
> ## 
> 
> Austin Rutherford | Director, Field Strategy and Operations | Mobile:
> 612-386-4197 | Twitter: @AP_Rutherford
> 
> Pivotal.io
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2#issuecomment-90369978.
> 
> Chuck Svoboda mailto:notifications@github.com
> 4 April 2015 06:38
> 
> The JSON file requests the us-east-1b availability zone. This no 
> longer exists. I found success using us-east-1a. Maybe update to this 
> or c, d, or e. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Pivotal-Field-Engineering/PCF_AWS_CloudFormation/issues/2.

## 

Simon Elisha
CTO & Director of Field Engineering - Australia & New Zealand
Mobile: +61 417 656 364
e-mail: selisha@pivotal.io mailto:selisha@pivotal.io
http://www.gopivotal.com
pivotal.io http://pivotal.io
